# Site settings
title: Soont
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  一个记录计算机技术、建筑技术的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.soont.com" # the base hostname & protocol for your site
permalink: /:categories/:title.html
favicon: /favicon.ico


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   maucat
# codepen:  username
# dribbble: username


# Comment
duoshuo_shortname: blogsoont


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
